# PURL configuration for http://purl.obolibrary.org/obo/cvdo

idspace: CVDO
base_url: /obo/cvdo

products:
- cvdo.owl: https://raw.githubusercontent.com/OpenLHS/CVDO/master/cvdo.owl

term_browser: ontobee
example_terms:
- CVDO_0000010
